In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv("Social_Network_Ads.csv")

In [5]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [7]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first=True)

In [9]:
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [11]:
datatset=dataset.drop("User ID",axis=1)

In [13]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [15]:
independent=dataset[['Age', 'EstimatedSalary', 'Gender_Male']]

In [17]:
dependent=dataset[['Purchased']]

In [19]:
independent

Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [21]:
dependent

Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [27]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=50,max_features=None)
classifier.fit(X_train,Y_train)

C:\Anaconda\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(max_features=None, n_estimators=50)

In [29]:
Y_predict = classifier.predict(X_test)

In [31]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,Y_predict)

In [33]:
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test,Y_predict)

In [35]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.95      0.92      0.94        79
           1       0.86      0.90      0.88        41

    accuracy                           0.92       120
   macro avg       0.90      0.91      0.91       120
weighted avg       0.92      0.92      0.92       120



In [37]:
print(cm)

[[73  6]
 [ 4 37]]


In [45]:
result = classifier.predict([[55,45000,1]])

C:\Anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [47]:
result

array([1], dtype=int64)

In [49]:
import pickle

In [53]:
filename = "Finalized_RandomForestClassifier_model.sav"
pickle.dump(classifier,open(filename,"wb"))

In [55]:
loaded_model = pickle.load(open("Finalized_RandomForestClassifier_model.sav",'rb'))

In [57]:
Age_input= float(input("Enter your Age :"))
EstimatedSalary_input=float(input("Enter your Salary amount  :"))
Gender_input=int(input("Enter Gender :"))

Enter your Age : 41
Enter your Salary amount  : 30000
Enter Gender : 1


In [59]:
result=loaded_model.predict([[Age_input,EstimatedSalary_input,Gender_input]])

C:\Anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [61]:
result

array([0], dtype=int64)